### ISSUE TITLE
Cursor Action throws an error on RX-V481D

### ISSUE THREAD

**Issue by YetAnotherPhil** [BirdAPI/yamaha-network-receivers#12]
Hi 
When I try to add a cursor action instead of (I presume) a dialogue popup the following appears in the log:
```
Traceback (most recent call last) (1722):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 59, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ConfigDialog.py", line 165, in Configure
    treeItem.Configure(*args)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionItem.py", line 101, in Configure
    return self.executable.Configure(*args)
  File "C:\Program Files (x86)\EventGhost\plugins\yamaha-network-receivers\client.py", line 438, in Configure
    zones = get_available_zones(self.plugin, True, globals.All_ZONES_PLUS_ACTIVE, limit=2)
AttributeError: 'module' object has no attribute 'All_ZONES_PLUS_ACTIVE'
Traceback (most recent call last) (1722):
  File "wx\_core.pyc", line 14669, in <lambda>
  File "C:\Program Files (x86)\EventGhost\eg\Core.py", line 197, in Notify
    listener(value)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\MainFrame\TreeCtrl.py", line 844, in OnNodeSelected
    path = node.GetPath()
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TreeItem.py", line 377, in GetPath
    path.append(parent.childs.index(item))
AttributeError: 'NoneType' object has no attribute 'childs'
```

Any help much appreciated.

Thanks
Phil

**Comment by YetAnotherPhil** [comment]
Updated to Latest pre-release EventGhost from http://www.eventghost.net/downloads/ & error changed to the following:

```
Traceback (most recent call last) (0.5.0-rc4):
  File "C:\Program Files (x86)\EventGhost\eg\Classes\TaskletDialog.py", line 162, in ProcessingTask
    self.Configure(*args, **kwargs)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ConfigDialog.py", line 106, in Configure
    treeItem.Configure(*args)
  File "C:\Program Files (x86)\EventGhost\eg\Classes\ActionItem.py", line 80, in Configure
    return self.executable.Configure(*args)
  File "C:\Program Files (x86)\EventGhost\plugins\yamaha-network-receivers\client.py", line 438, in Configure
    zones = get_available_zones(self.plugin, True, globals.All_ZONES_PLUS_ACTIVE, limit=2)
AttributeError: 'module' object has no attribute 'All_ZONES_PLUS_ACTIVE'
```
TIA

**Comment by YetAnotherPhil** [comment]
It's a typo error All_ZONES_PLUS_ACTIVE should be ALL_ZONES_PLUS_ACTIVE

i.e. uppercase L's in ALL
